gui:
  # Show nerd icons (notably for files in staged list)
  mouseEvents: true
  nerdFontsVersion: "3"

  returnImmediately: true

  # Color theme
  theme:
    activeBorderColor:
      - blue
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

customCommands:
  containers:
    - name: bash
      attach: true
      command: "docker exec -it {{ .Container.ID }} bash"
      serviceNames: []
    - name: reset-project
      shell: true
      command: "{{ .DockerCompose }} -p {{ .Container.ProjectName }} down -v && {{ .DockerCompose }} -p {{ .Container.ProjectName }} up -d --build"
      serviceNames: []
  services:
    - name: reset-project
      attach: true
      command: "{{ .DockerCompose }} down -v && {{ .DockerCompose }} up -d --build"
      serviceNames: []
    - name: up-build
      attach: true
      command: "{{ .DockerCompose }} down -v && {{ .DockerCompose }} up -d --build"
      serviceNames: []
