gui:
  # Show nerd icons (notably for files in staged list)
  mouseEvents: true
  nerdFontsVersion: "3"

  # Color theme
  theme:
    activeBorderColor:
      - blue
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
