[include]
files = ['modules/']

[desktop_widgets]
enabled = false

[location]
auto_locate = true

[notification]
background_opacity = 0.59999998658895493
border = false
show_actions = false
show_app_name = false

[osd]
background_opacity = 0.99999997764825821
border = true
position = "bottom_center"
position_vertical = "center_right"

[osd.kinds]
media = false

[plugin_settings."yuuto/arch-updater"]
aur_helper = "paru"
auto_check_hours = 1
check_arch_news = false
flatpak_enabled = false
notify_on_updates = false

[plugins]
enabled = ["noctalia/bongocat", "yuuto/arch-updater"]

[shell]
clipboard_enabled = false
font_family = "Maple Mono NF"
lang = "en"
password_style = "random"
telemetry_enabled = true

[shell.panel]
borders = true
session_placement = "floating"
session_position = "center"
transparency_mode = "glass"

[shell.screenshot]
directory = "/home/nino/Pictures/Screenshots"

[shell.session]
grid_columns = 5
show_shortcuts = false

[[shell.session.actions]]
action = "lock"
countdown_seconds = 0.0
enabled = true
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
countdown_seconds = 0.0
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "reboot"
countdown_seconds = 0.0
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
countdown_seconds = 0.0
enabled = true
shortcut = "5"
variant = "destructive"

[theme]
builtin = "Noctalia"
community_palette = "Atuel"
custom_palette = "catppuccin_mocha"
mode = "dark"
source = "custom"

[wallpaper]
directory = "/home/nino/Pictures/Wallpapers"

[wallpaper.default]
path = "/home/nino/Pictures/Wallpapers/catppuccin/abstract-3D-cubes.png.png"

[wallpaper.last]
path = "/home/nino/Pictures/Wallpapers/catppuccin/abstract-3D-cubes.png.png"

[wallpaper.monitors.DP-1]
path = "/home/nino/Pictures/Wallpapers/catppuccin/abstract-3D-cubes.png.png"

[wallpaper.monitors.DP-2]
path = "/home/nino/Pictures/Wallpapers/catppuccin/abstract-3D-cubes.png.png"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/clouds-darker.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/sand-dune.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/festival-before-fight.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/boy-on-windmill-light.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/flowers-pink.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/japanese-fullmoon.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/perfect-blue.png"
theme_mode = "dark"

[[wallpaper.favorite]]
path = "/home/nino/Pictures/Wallpapers/catppuccin/abstract-3D-cubes.png.png"
theme_mode = "auto"
