[bar.default]
background_opacity = 0.64999998547136784
center = ["workspaces", "clock"]
concave_edge_corners = true
end = [
  "tray",
  "widget",
  "network",
  "bluetooth",
  "volume",
  "brightness",
  "battery",
  "notifications",
]
font_family = "Maple Mono NF"
margin_edge = 16
margin_ends = 16
start = ["control-center", "spacer_2", "group:g1", "weather", "bar", "cat"]
widget_spacing = 10

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g1"
members = ["audio_visualizer", "media"]
opacity = 1.0
padding = 10.0
widget_spacing = 6

[config.custom_colors]
teal = "#94e2d5"

[desktop_widgets]
enabled = false

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.0
monitors = ["DP-3"]

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
  "lockscreen-login-box@DP-3",
  "lockscreen-login-box@DP-2",
  "lockscreen-widget-0000000000000001",
  "lockscreen-widget-0000000000000002",
  "lockscreen-widget-0000000000000004",
  "lockscreen-widget-0000000000000005",
  "lockscreen-widget-0000000000000006",
  "lockscreen-widget-0000000000000007",
  "lockscreen-widget-0000000000000008",
  "lockscreen-widget-0000000000000009",
  "lockscreen-widget-000000000000000a",
  "lockscreen-widget-000000000000000d",
  "lockscreen-widget-000000000000000b",
  "lockscreen-widget-000000000000000e",
  "lockscreen-widget-000000000000000c",
  "lockscreen-widget-000000000000000f",
]

[lockscreen_widgets.grid]
cell_size = 8
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
background_color = "surface_variant"
background_opacity = 0.0
background_radius = 12.0
center_password_text = false
input_opacity = 0.80000000000000004
input_radius = 6.0
layout = "compact"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = false
show_media = false
show_session_buttons = true
show_unlock_hint = false
show_weather = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
box_height = 70.0
box_width = 384.0
cx = 1280.0
cy = 1248.0
output = "DP-2"
placement_height = 0.0
placement_width = 0.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = true
input_opacity = 1.0
input_radius = 6.0
layout = "compact"
show_caps_lock = true
show_keyboard_layout = false
show_login_button = false
show_media = true
show_session_buttons = true
show_unlock_hint = false
show_weather = false

[lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
box_height = 70.0
box_width = 416.0
cx = 1280.0
cy = 1251.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
background_color = "surface_variant"
background_opacity = 0.0
background_radius = 12.0
center_password_text = true
input_opacity = 0.80000000000000004
input_radius = 6.0
layout = "compact"
show_caps_lock = false
show_keyboard_layout = false
show_login_button = false
show_media = true
show_session_buttons = true
show_unlock_hint = false
show_weather = true

[lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
box_height = 144.0
box_width = 512.0
cx = 1280.0
cy = 600.0
output = "DP-2"
placement_height = 0.0
placement_width = 0.0
rotation = 0.0
type = "clock"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
background = false
background_opacity = 0.59999999999999998
background_padding = 4
center_text = true
clock_style = "digital"
color = "primary"
font_family = "Inter Display"
format = "{:%H:%M}"
shadow = false

[lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
box_height = 48.0
box_width = 336.0
cx = 1280.0
cy = 720.0
output = "DP-2"
placement_height = 0.0
placement_width = 0.0
rotation = 0.0
type = "clock"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
background = false
center_text = true
font_family = "Inter Display"
format = "{:%a %d %b}"
shadow = false

[lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
box_height = 96.0
box_width = 176.0
cx = 1176.0
cy = 1152.0
output = "DP-2"
placement_height = 0.0
placement_width = 0.0
rotation = 0.0
type = "weather"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
background = true
background_color = "surface"
background_opacity = 0.80000000000000004
background_padding = 10
background_radius = 12
color = "on_surface"
font_family = ""
forecast_days = 3
shadow = true
show_forecast = false

[lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
box_height = 96.0
box_width = 176.0
cx = 1384.0
cy = 1152.0
output = "DP-2"
placement_height = 0.0
placement_width = 0.0
rotation = 0.0
type = "sysmon"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
background = true
background_color = "surface"
background_opacity = 0.80000000000000004
background_padding = 7
background_radius = 12
color = "primary"
color2 = "secondary"
display = "graph"
font_family = ""
gauge_layout = "horizontal"
highlight_color = "error"
interface = ""
label_min_width = 0
network_speed_compact = false
network_speed_unit = "auto"
shadow = true
show_label = true
stat = "cpu_usage"
stat2 = "cpu_freq"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
box_height = 144.0
box_width = 504.0
cx = 1284.0
cy = 592.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "clock"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
background = false
background_opacity = 0.59999999999999998
background_padding = 4
center_text = true
clock_style = "digital"
color = "primary"
font_family = "Inter Display"
format = "{:%H:%M}"
shadow = false

[lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
box_height = 56.0
box_width = 264.0
cx = 1280.0
cy = 720.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "clock"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
background = false
center_text = true
font_family = "Inter Display"
format = "{:%a %d %b}"
shadow = false

[lockscreen_widgets.widget.lockscreen-widget-0000000000000008]
box_height = 240.0
box_width = 240.0
cx = 1288.0
cy = 888.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "fancy_audio_visualizer"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000008.settings]
background = false
background_color = "surface"
background_opacity = 0.80000000000000004
background_padding = 10
background_radius = 12
bar_width = 0.60000000000000009
bloom_intensity = 0.0
fade_when_idle = true
inner_diameter = 0.69999999999999996
primary_color = "primary"
ring_opacity = 0.0
rotation_speed = 0.20000000000000001
secondary_color = "primary"
sensitivity = 1.5
visualization_mode = "bars_rings"
wave_thickness = 1.0

[lockscreen_widgets.widget.lockscreen-widget-0000000000000009]
box_height = 120.0
box_width = 176.0
cx = 1176.0
cy = 1148.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "weather"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000009.settings]
background = true
background_color = "surface"
background_opacity = 0.80000000000000004
background_padding = 10
background_radius = 12
color = "on_surface"
font_family = ""
forecast_days = 3
shadow = true
show_forecast = false

[lockscreen_widgets.widget.lockscreen-widget-000000000000000a]
box_height = 120.0
box_width = 176.0
cx = 1384.0
cy = 1148.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "sysmon"

[lockscreen_widgets.widget.lockscreen-widget-000000000000000a.settings]
background = true
background_color = "surface"
background_opacity = 0.80000000000000004
background_padding = 7
background_radius = 12
color = "primary"
color2 = "tertiary"
display = "graph"
font_family = ""
gauge_layout = "horizontal"
highlight_color = "error"
interface = ""
label_min_width = 0
network_speed_compact = false
network_speed_unit = "auto"
shadow = true
show_label = true
stat = "gpu_usage"
stat2 = "cpu_usage"

[lockscreen_widgets.widget.lockscreen-widget-000000000000000b]
box_height = 64.0
box_width = 64.0
cx = 1232.0
cy = 1328.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "button"

[lockscreen_widgets.widget.lockscreen-widget-000000000000000b.settings]
background = false
command = "noctalia msg session reboot"
glyph = "reload"
variant = "outline"

[lockscreen_widgets.widget.lockscreen-widget-000000000000000c]
box_height = 64.0
box_width = 64.0
cx = 1328.0
cy = 1328.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "button"

[lockscreen_widgets.widget.lockscreen-widget-000000000000000c.settings]
background = false
color = "error"
command = "noctalia msg session shutdown"
glyph = "shutdown"
variant = "default"

[lockscreen_widgets.widget.lockscreen-widget-000000000000000d]
box_height = 64.0
box_width = 64.0
cx = 1232.0
cy = 1328.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "label"

[lockscreen_widgets.widget.lockscreen-widget-000000000000000d.settings]
opacity = 0.0

[lockscreen_widgets.widget.lockscreen-widget-000000000000000e]
box_height = 64.0
box_width = 64.0
cx = 1328.0
cy = 1328.0
output = "DP-3"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "label"

[lockscreen_widgets.widget.lockscreen-widget-000000000000000e.settings]
opacity = 0.0

[lockscreen_widgets.widget.lockscreen-widget-000000000000000f]
box_height = 0.0
box_width = 0.0
cx = 1280.0
cy = 816.0
output = "DP-2"
placement_height = 0.0
placement_width = 0.0
rotation = 0.0
type = "audio_visualizer"

[lockscreen_widgets.widget.lockscreen-widget-000000000000000f.settings]
background = false
bands = 8
show_when_idle = true

[notification]
background_opacity = 0.59999998658895493
border = false
show_actions = false
show_app_name = false

[osd]
background_opacity = 0.99999997764825821
border = true
position = "bottom_center"
position_vertical = "center_right"

[osd.kinds]
media = false

[plugin_settings."yuuto/arch-updater"]
aur_helper = "paru"
auto_check_hours = 1
check_arch_news = false
flatpak_enabled = false
notify_on_updates = false

[plugins]
enabled = ["noctalia/bongocat", "yuuto/arch-updater"]

[shell]
clipboard_enabled = false
font_family = "Maple Mono NF"
lang = "en"
password_style = "random"
telemetry_enabled = true

[shell.panel]
borders = true
session_placement = "floating"
session_position = "center"
transparency_mode = "glass"

[shell.screenshot]
directory = "/home/nino/Pictures/Screenshots"

[shell.session]
grid_columns = 5
show_shortcuts = false

[[shell.session.actions]]
action = "lock"
countdown_seconds = 0.0
enabled = true
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
countdown_seconds = 0.0
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "reboot"
countdown_seconds = 0.0
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
countdown_seconds = 0.0
enabled = true
shortcut = "5"
variant = "destructive"

[theme]
builtin = "Tokyo-Night"
community_palette = "Atuel"
custom_palette = "catppuccin_mocha"
source = "custom"

[theme.templates]
builtin_ids = ["gtk3", "gtk4", "qt", "starship"]
community_ids = ["bat"]
enable_builtin_templates = true
enable_community_templates = true

[theme.templates.user.eza]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/eza/eza.yml"
output_path = "$XDG_CONFIG_HOME/eza/theme.yml"

[wallpaper]
directory = "/home/nino/.local/share/wallpapers/catppuccin"

[wallpaper.default]
path = "/home/nino/.local/share/wallpapers/catppuccin/clouds-darker.png"

[[wallpaper.favorite]]
builtin_palette = "Noctalia"
palette_source = "builtin"
path = "/home/nino/.local/share/wallpapers/catppuccin/clouds-darker.png"
theme_mode = "dark"

[widget.audio_visualizer]
bands = 3
mirrored = true
width = 35

[widget.bar]
extras = "none"
provider_limit = 2
style = "meter"
type = "felipeartur/ai-usagebar:bar"

[widget.cat]
input_devices = ["/dev/input/event*"]
type = "noctalia/bongocat:cat"

[widget.clock]
format = "{:%a %d %b %H:%M}"
timezone = "Europe/Paris"
vertical_format = "{:%a %H:%M}"

[widget.control-center]
capsule_fill = "on_primary"
capsule_padding = 9
color = "primary"
custom_image = "/home/nino/.local/share/icons/custom/cachy-os-colored.svg"
custom_image_colorize = true
glyph = ""
scale = 1.25

[widget.media]
artist_first = true
hide_album_art = true
hide_when_no_media = true
max_length = 200
title_scroll = "on_hover"

[widget.network]
show_vpn_label = true

[widget.spacer_2]
type = "spacer"

[widget.tray]
drawer = true
hidden = ["nm-applet", "blueman", "org.kde.StatusNotifierItem-1-1"]
match_adjacent_spacing = true

[widget.volume]
show_label = false

[widget.weather]
icon_color = "primary"
show_condition = false

[widget.widget]
glyph = "cloud-download"
hide_on_empty = true
type = "yuuto/arch-updater:widget"

[widget.workspaces]
empty_color = "outline"
hide_when_empty = false
occupied_color = "outline"
show_labels = false
urgent_color = "outline"
