[include]
files = ['modules/']

[bar.default]
background_opacity = 0.64999998547136784
capsule_thickness = 0.69999998807907104
center = ["workspaces", "clock"]
concave_edge_corners = true
end = [
  "tray",
  "widget",
  "network",
  "bluetooth",
  "volume",
  "brightness",
  "battery",
  "notifications",
]
font_family = "RecMonoCasual Nerd Font"
margin_edge = 16
margin_ends = 16
start = ["control-center", "spacer_2", "group:g1", "weather", "bar", "cat"]
thickness = 36
widget_spacing = 10

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "primary"
id = "g1"
members = ["audio_visualizer", "media"]
opacity = 0.10000000149011612
padding = 10.0
widget_spacing = 6

[desktop_widgets]
enabled = false

[location]
auto_locate = true

[notification]
background_opacity = 0.59999998658895493
border = false
show_actions = false
show_app_name = false

[osd]
background_opacity = 0.99999997764825821
border = true
position = "bottom_center"
position_vertical = "center_right"

[osd.kinds]
media = false

[plugin_settings."yuuto/arch-updater"]
aur_helper = "paru"
auto_check_hours = 1
check_arch_news = false
flatpak_enabled = false
notify_on_updates = false

[plugins]
enabled = ["noctalia/bongocat", "yuuto/arch-updater"]

[shell]
clipboard_enabled = false
font_family = "Maple Mono NF"
lang = "en"
password_style = "random"
telemetry_enabled = true

[shell.panel]
borders = true
session_placement = "floating"
session_position = "center"
transparency_mode = "glass"

[shell.screenshot]
directory = "/home/nino/Pictures/Screenshots"

[shell.session]
grid_columns = 5
show_shortcuts = false

[[shell.session.actions]]
action = "lock"
countdown_seconds = 0.0
enabled = true
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
countdown_seconds = 0.0
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "reboot"
countdown_seconds = 0.0
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
countdown_seconds = 0.0
enabled = true
shortcut = "5"
variant = "destructive"

[theme]
builtin = "Noctalia"
community_palette = "Atuel"
custom_palette = "catppuccin_mocha"
source = "custom"


[wallpaper]
directory = "/home/nino/.local/share/wallpapers/catppuccin"

[wallpaper.default]
path = "/home/nino/tmp/lutgen/w78.png"

[wallpaper.last]
path = "/home/nino/tmp/lutgen/w78.png"

[wallpaper.monitors.DP-1]
path = "/home/nino/tmp/lutgen/w78.png"

[wallpaper.monitors.DP-2]
path = "/home/nino/tmp/lutgen/w78.png"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/clouds-darker.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/sand-dune.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/festival-before-fight.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/boy-on-windmill-light.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/flowers-pink.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/japanese-fullmoon.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "catppuccin_mocha"
palette_source = "custom"
path = "/home/nino/.local/share/wallpapers/catppuccin/perfect-blue.png"
theme_mode = "dark"

[widget.audio_visualizer]
bands = 3
font_scale = 0.95000000000000007
mirrored = true
width = 35

[widget.bar]
extras = "none"
provider_limit = 2
style = "meter"
type = "felipeartur/ai-usagebar:bar"

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.cat]
input_devices = ["/dev/input/event*"]
type = "noctalia/bongocat:cat"

[widget.clock]
format = "{:%a %d %b %H:%M}"
timezone = "Europe/Paris"
vertical_format = "{:%a %H:%M}"

[widget.control-center]
capsule_fill = "on_primary"
capsule_padding = 9
color = "primary"
custom_image = "/home/nino/.local/share/icons/custom/cachy-os-colored.svg"
custom_image_colorize = true
glyph = ""
scale = 1.25

[widget.media]
artist_first = true
color = "primary"
font_scale = 0.95000000000000007
hide_album_art = true
hide_when_no_media = true
max_length = 200
title_scroll = "on_hover"

[widget.network]
show_vpn_label = true

[widget.spacer_2]
type = "spacer"

[widget.tray]
drawer = true
hidden = ["nm-applet", "blueman", "org.kde.StatusNotifierItem-1-1"]
match_adjacent_spacing = true

[widget.volume]
show_label = false

[widget.weather]
icon_color = "tertiary"
show_condition = false

[widget.widget]
glyph = "cloud-download"
hide_on_empty = true
type = "yuuto/arch-updater:widget"

[widget.workspaces]
empty_color = "surface_variant"
focused_output_only = true
hide_when_empty = false
occupied_color = "surface_variant"
show_labels = false
urgent_color = "error"
