[theme.templates]
enable_builtin_templates = true
enable_community_templates = true
builtin_ids = ["gtk3", "gtk4", "ghostty", "qt", "starship"]
community_ids = ["bat"]

[theme.templates.user.eza]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/eza/eza.yml"
output_path = "$XDG_CONFIG_HOME/eza/theme.yml"

[theme.templates.user.fastfetch]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/eza/eza.yml"
output_path = "$XDG_CONFIG_HOME/eza/theme.yml"

[theme.templates.user.zen_browser_chrome]
input_path = "templates/zen-browser/zen-userChrome.css"
output_path = "$XDG_CACHE_HOME/noctalia/zen-browser/zen-userChrome.css"
post_hook = "bash '{{ config_dir }}/templates/zen-browser/apply.sh'"

[theme.templates.user.zen_browser_content]
input_path = "templates/zen-browser/zen-userContent.css"
output_path = "$XDG_CACHE_HOME/noctalia/zen-browser/zen-userContent.css"
post_hook = "bash '{{ config_dir }}/templates/zen-browser/apply.sh'"
