[theme.templates]
enable_builtin_templates = true
enable_community_templates = true
builtin_ids = ["gtk3", "gtk4", "ghostty", "qt", "starship"]
community_ids = ["bat"]

[theme.templates.user.eza]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/eza/eza.yml"
output_path = "$XDG_CONFIG_HOME/eza/theme.yml"

[theme.templates.user.fastfetch]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/eza/eza.yml"
output_path = "$XDG_CONFIG_HOME/eza/theme.yml"

[theme.templates.user.zen_browser_chrome]
input_path = "templates/zen-browser/zen-userChrome.css"
output_path = "$XDG_CACHE_HOME/noctalia/zen-browser/zen-userChrome.css"
post_hook = "bash '{{ config_dir }}/templates/zen-browser/apply.sh'"

[theme.templates.user.zen_browser_content]
input_path = "templates/zen-browser/zen-userContent.css"
output_path = "$XDG_CACHE_HOME/noctalia/zen-browser/zen-userContent.css"
post_hook = "bash '{{ config_dir }}/templates/zen-browser/apply.sh'"

[theme.templates.user.yazi]
input_path = "templates/yazi/yazi.toml"
output_path = "$XDG_CONFIG_HOME/yazi/flavors/noctalia.yazi/flavor.toml"
post_hook = "bash '{{ config_dir }}/templates/yazi/apply.sh'"

[theme.templates.user.yazi-syntax]
input_path = "templates/yazi/yazi.tmTheme"
output_path = "$XDG_CONFIG_HOME/yazi/flavors/noctalia.yazi/tmtheme.xml"

[theme.templates.user.lazygit]
input_path = "templates/lazygit/lazygit.yml"
output_path = "$XDG_CONFIG_HOME/lazygit/theme.yml"

[theme.templates.user.fzf]
input_path = "templates/fzf/fzfrc"
output_path = "$XDG_CONFIG_HOME/fzf/fzfrc"
