# Launch notification daemon
# exec-once = mako

# Launch hyprpanel
# exec-once = hyprpanel

# Export the current Wayland session env to systemd and D-Bus activation.
# exec-once = /usr/lib/ibus/ibus-ui-gtk3 --enable-wayland-im --exec-daemon --daemon-args "--xim --panel disable"

# Launch waybar
exec-once = waybar -c ~/.config/waybar/config-bar.jsonc -s ~/.config/waybar/style-bar.css

# Launch swaync
exec-once = swaync

# Launch swayosd
exec-once = swayosd-server -s ~/.config/swayosd/style.css

# Launch awww daemon
exec-once = awww-daemon

# Launch walker service
exec-once = walker --gapplication-service

# Launch vicinae service
exec-once = vicinae server

# Set clipboard manager
exec-once = wl-paste --type text --watch cliphist store 

exec-once = $terminal

exec-once = [workspace 2] $browser

# Launch btop in special btop workspace
exec-once = [workspace special:btop silent] $terminal -e "btop"
