# Launch notification daemon
exec-once = mako

# Launch hyprpanel
exec-once = hyprpanel

# Launch awww daemon
exec-once = awww-daemon

# Launch walker service
exec-once = walker --gapplication-service

# Launch vicinae service
exec-once = vicinae server

# Set clipboard manager
exec-once = wl-paste --type text --watch cliphist store 

exec-once = $terminal

exec-once = obsidian

# Launch terminal in special term workspace
exec-once = [workspace special:term silent] $terminal -e "opencode"

# Launch opencode in special term workspace
exec-once = [workspace special:term silent] $terminal

# Launch btop in special btop workspace
exec-once = [workspace special:btop silent] $terminal -e "btop"
