# define the list of game classes
$games = Steam Lutris Heroic HeroicGamesLauncher Proton shadps4

# Send browser to workspace 2
windowrule = workspace 2, match:class zen

# Send Steam/lutris games to special workspace "game"
windowrule = workspace special:game, match:class ^(steam)$
windowrule = workspace special:game, match:class ^(Steam)$
windowrule = workspace special:game, match:class ^(steam_app_.*)$
windowrule = workspace special:game, match:class ^(net.lutris.Lutris)$
windowrule = workspace special:game, match:class ^(BB_Launcher)$

# Send vesktop/discord to special workspace "discord"
windowrule = workspace special:discord, match:class vesktop

# Send obsidian to special workspace "note"
windowrule = workspace special:note, match:class obsidian

# apply rules to those classes
windowrule = no_anim on, no_blur on, no_shadow on, border_size 0, rounding 0, fullscreen on, immediate on, match:class $games

# Make app transparents
windowrule = match:class Codex, opacity 0.99
windowrule = match:class org.gnome.Nautilus, opacity 0.90
windowrule = match:class nwg-look, opacity 0.90
windowrule = match:class io.github.kaii_lb.Overskride, opacity 0.90
windowrule = match:class ^(org.gnome.*)$, opacity 0.9

# Make browsers not become transparent when inactive
windowrule = match:class microsoft-edge, opacity 1.0 override
windowrule = match:class helium, opacity 1.0 override
windowrule = match:class vivaldi-stable, opacity 1.0 override

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Add blur to mako notifications
layerrule = blur on, ignore_alpha 0.5, match:namespace notifications

# Add blur to vicinae launcher
layerrule = blur on, ignore_alpha 0.5, match:namespace vicinae

# Add blur to swaync launcher
layerrule = blur on, ignore_alpha 0.5, match:namespace swayosd
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-notification-window

# Add blur to walker launcher
# layerrule = blur on, ignore_alpha 0.5, match:namespace walker
