# fish completion for noctalia; generated from the live CLI schema
function __noctalia_path_prefix
    set -l tokens (commandline -opc)
    if test (count $tokens) -gt 0
        set -e tokens[1]
    end
    for segment in $argv
        if test (count $tokens) -eq 0; or test $tokens[1] != $segment
            return 1
        end
        set -e tokens[1]
    end
    return 0
end

function __noctalia_exact_path
    set -l tokens (commandline -opc)
    if test (count $tokens) -gt 0
        set -e tokens[1]
    end
    if test (count $tokens) -ne (count $argv)
        return 1
    end
    for segment in $argv
        if test $tokens[1] != $segment
            return 1
        end
        set -e tokens[1]
    end
    return 0
end

function __noctalia_at_pos
    set -l wanted $argv[1]
    set -e argv[1]
    set -l tokens (commandline -opc)
    if test (count $tokens) -gt 0
        set -e tokens[1]
    end
    for segment in $argv
        if test (count $tokens) -eq 0; or test $tokens[1] != $segment
            return 1
        end
        set -e tokens[1]
    end
    set -l seen 0
    for token in $tokens
        if not string match -qr '^-' -- $token
            set seen (math $seen + 1)
        end
    end
    test $seen -eq $wanted
end

function __noctalia_plugins_enabled
    noctalia msg plugins list 2>/dev/null | awk '$4 == "enabled" {print $1}'
end

function __noctalia_plugins_disabled
    noctalia msg plugins list 2>/dev/null | awk '$4 == "disabled" {print $1}'
end

function __noctalia_plugin_prefix
    noctalia msg plugins list 2>/dev/null | awk '$4 == "enabled" {print $1":"}'
end

complete -c noctalia -n '__noctalia_exact_path' -f -a 'completions' -d 'Generate shell completion scripts'
complete -c noctalia -n '__noctalia_exact_path' -f -a 'config' -d 'Validate config and support/replay helpers'
complete -c noctalia -n '__noctalia_exact_path' -f -a 'dmenu' -d 'Read launcher choices from stdin'
complete -c noctalia -n '__noctalia_exact_path' -f -a 'firefox-theme' -d 'Manage Firefox theme integration'
complete -c noctalia -n '__noctalia_exact_path' -f -a 'msg' -d 'Send a command to the running instance'
complete -c noctalia -n '__noctalia_exact_path' -f -a 'plugins' -d 'Offline plugin author tools'
complete -c noctalia -n '__noctalia_exact_path' -f -a 'theme' -d 'Generate a color palette from an image'
complete -c noctalia -n '__noctalia_path_prefix' -s v -l version -d 'Show version information'
complete -c noctalia -n '__noctalia_path_prefix' -s d -l daemon -d 'Run in background'
complete -c noctalia -n '__noctalia_path_prefix' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix completions' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 completions' -f -a 'bash fish zsh' -d 'Shell completion format'
complete -c noctalia -n '__noctalia_exact_path config' -f -a 'export' -d 'Print the active config as TOML'
complete -c noctalia -n '__noctalia_exact_path config' -f -a 'replay-report' -d 'Reconstruct config and state from a support report'
complete -c noctalia -n '__noctalia_exact_path config' -f -a 'settings-count' -d 'Count Settings UI controls'
complete -c noctalia -n '__noctalia_exact_path config' -f -a 'validate' -d 'Check config validity'
complete -c noctalia -n '__noctalia_path_prefix config' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix config export' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 config export' -f -a 'merged full' -d 'Export mode (default: merged)'
complete -c noctalia -n '__noctalia_path_prefix config replay-report' -l target -r -F -d 'Directory where replay files are written'
complete -c noctalia -n '__noctalia_path_prefix config replay-report' -l flattened -d 'Write only merged_config.content as config.toml'
complete -c noctalia -n '__noctalia_path_prefix config replay-report' -l force -d 'Remove an existing target directory before writing'
complete -c noctalia -n '__noctalia_path_prefix config replay-report' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix config settings-count' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix config validate' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix dmenu' -s p -l prompt -r -F -d 'Set the launcher prompt'
complete -c noctalia -n '__noctalia_path_prefix dmenu' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix firefox-theme' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 firefox-theme' -f -a 'install uninstall update dark light auto host start help' -d 'Action to perform'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bar-auto-hide-set' -d 'Set auto-hide state for a bar'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bar-hide' -d 'Hide one or all bars and release their layout gaps'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bar-layer-set' -d 'Set one or all bar layers'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bar-reserve-toggle' -d 'Toggle reserve space for one or all bars'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bar-show' -d 'Show one or all bars'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bar-toggle' -d 'Toggle visibility for one or all bars'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bluetooth-disable' -d 'Disable Bluetooth'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bluetooth-enable' -d 'Enable Bluetooth'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bluetooth-status' -d 'Print Bluetooth state'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'bluetooth-toggle' -d 'Toggle Bluetooth'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'brightness-down' -d 'Decrease brightness (defaults to current monitor)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'brightness-list-backlight-devices' -d 'List available sysfs backlight device names'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'brightness-osd' -d 'Show brightness OSD without changing brightness'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'brightness-set' -d 'Set brightness (defaults to current monitor)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'brightness-up' -d 'Increase brightness (defaults to current monitor)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'caffeine-disable' -d 'Disable caffeine (idle inhibitor)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'caffeine-enable' -d 'Enable caffeine (idle inhibitor)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'caffeine-toggle' -d 'Toggle caffeine (idle inhibitor)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'clipboard-clear' -d 'Clear clipboard history'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'clipboard-copy' -d 'Copy text to the clipboard'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'clipboard-text' -d 'Print the most recent clipboard text (empty when the selection holds no text)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'color-scheme-get' -d 'Print active color scheme: <source> <name> (source is builtin, wallpaper, community, or custom)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'color-scheme-set' -d 'Set palette source and selection in settings.toml (builtin name, wallpaper generator scheme, community id, or custom scheme folder name)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'config-reload' -d 'Reload the config file'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'desktop-widgets-edit' -d 'Open the desktop widgets editor'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'desktop-widgets-exit' -d 'Close the desktop widgets editor'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'desktop-widgets-hide' -d 'Hide desktop widgets now (runtime only; does not change the saved setting)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'desktop-widgets-show' -d 'Show desktop widgets now (runtime only; does not change the saved setting)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'desktop-widgets-toggle' -d 'Toggle desktop widgets visibility (runtime only; does not change the saved setting)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'desktop-widgets-toggle-edit' -d 'Toggle desktop widgets edit mode'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'dock-hide' -d 'Hide the dock (persists override)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'dock-reload' -d 'Reload dock configuration'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'dock-show' -d 'Show the dock (persists override)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'dock-toggle' -d 'Toggle dock visibility (persists override)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'dpms-off' -d 'Turn monitors off'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'dpms-on' -d 'Turn monitors on'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'effects-profile-set' -d 'Set the EasyEffects output or input profile'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'greeter-sync' -d 'Sync wallpaper, colors, and monitor layout to Noctalia Greeter'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'keyboard-backlight-down' -d 'Decrease all keyboard backlights by one level'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'keyboard-backlight-osd' -d 'Show keyboard backlight OSD without changing brightness'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'keyboard-backlight-set' -d 'Set all keyboard backlights (0-100 percentage)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'keyboard-backlight-toggle' -d 'Toggle all keyboard backlights on/off'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'keyboard-backlight-up' -d 'Increase all keyboard backlights by one level'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'keyboard-layout-cycle' -d 'Switch to the next keyboard layout'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'lockscreen-widgets-edit' -d 'Open the lockscreen widgets editor'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'lockscreen-widgets-exit' -d 'Close the lockscreen widgets editor'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'lockscreen-widgets-toggle-edit' -d 'Toggle lockscreen widgets edit mode'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'log-level-set' -d 'Set the console log level'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'log-level-status' -d 'Print the current console log level'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'media' -d 'Control active media playback'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'mic-mute' -d 'Toggle microphone mute'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'mic-volume-down' -d 'Decrease microphone volume'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'mic-volume-osd' -d 'Show the microphone volume OSD without changing volume (defaults to the current volume)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'mic-volume-set' -d 'Set microphone volume'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'mic-volume-up' -d 'Increase microphone volume'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'network-toggle' -d 'Disconnect the active network, or reconnect when nothing is connected'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'nightlight-disable' -d 'Disable night light schedule'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'nightlight-enable' -d 'Enable night light schedule'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'nightlight-force-toggle' -d 'Toggle forced night light mode'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'nightlight-toggle' -d 'Toggle night light schedule'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'notification-clear-active' -d 'Dismiss all currently active notifications'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'notification-clear-history' -d 'Clear notification history'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'notification-dnd-set' -d 'Set notification Do Not Disturb state'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'notification-dnd-status' -d 'Print notification Do Not Disturb state'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'notification-dnd-toggle' -d 'Toggle notification Do Not Disturb state'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'notification-invoke-latest' -d 'Invoke the default action of the most recent active notification'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'notification-show' -d 'Show an internal Noctalia notification'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'osd-disable' -d 'Disable OSD popups'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'osd-enable' -d 'Enable OSD popups'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'osd-toggle' -d 'Toggle OSD popups'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'panel-close' -d 'Close the active panel, or close the named panel if it is active'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'panel-open' -d 'Open a panel by id, optionally with context (e.g. launcher /emo, control-center audio)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'panel-toggle' -d 'Toggle a panel by id, optionally with context (e.g. launcher /emo, control-center audio)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'plugin' -d 'Dispatch an event to a plugin entry'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'plugins' -d 'Manage plugins and sources (list/enable/disable/update, source list/add/remove)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'power-cycle' -d 'Step through UPower'\''s ordered profile list, forward by default (wraps)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'power-set' -d 'Set the UPower power profile (e.g. performance, balanced, power-saver)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'screenshot-fullscreen' -d 'Capture the focused monitor by default, pick interactively with pick, or all outputs with all'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'screenshot-region' -d 'Start an interactive region screenshot'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'session' -d 'Run a built-in session action'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'settings-close' -d 'Close the settings window'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'settings-open' -d 'Open the settings window, or focus it if already open, optionally at a specific section'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'settings-open-plugin' -d 'Open the settings window at a plugin'\''s settings (e.g. noctalia/notes)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'settings-open-widget' -d 'Open the settings window at a bar widget; from a widget gesture, targets that widget'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'settings-toggle' -d 'Toggle the settings window, optionally at a specific section'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'status' -d 'Print current state as JSON'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'taskbar-cycle' -d 'Step to the adjacent task or workspace group in the invoking taskbar'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'templates-apply' -d 'Apply configured theme templates for the current palette'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'theme-mode-get' -d 'Print the current resolved theme mode'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'theme-mode-set' -d 'Set theme mode and persist to settings.toml'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'theme-mode-toggle' -d 'Toggle theme mode between dark and light'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'volume-down' -d 'Decrease speaker volume'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'volume-mute' -d 'Toggle speaker mute'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'volume-osd' -d 'Show the volume OSD without changing volume (defaults to the current volume)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'volume-set' -d 'Set speaker volume'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'volume-up' -d 'Increase speaker volume'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'wallpaper-get' -d 'Print default wallpaper path, or effective path for an output'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'wallpaper-next' -d 'Switch to the next wallpaper immediately'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'wallpaper-previous' -d 'Switch to the previous wallpaper immediately'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'wallpaper-random' -d 'Switch to a random wallpaper immediately'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'wallpaper-set' -d 'Set wallpaper for all or a specific output (persisted)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'wifi-disable' -d 'Disable Wi-Fi'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'wifi-enable' -d 'Enable Wi-Fi'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'wifi-status' -d 'Print Wi-Fi state'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'wifi-toggle' -d 'Toggle Wi-Fi'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'window-switcher' -d 'Open or close the window switcher overlay'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'workspace-alert-add' -d 'Add a workspace alert (by number, name, or id)'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'workspace-alert-add-window' -d 'Add a workspace alert for a window'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'workspace-alert-clear' -d 'Clear a workspace alert'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'workspace-alert-clear-all' -d 'Clear all workspace alerts'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'workspace-alert-status' -d 'Print workspace alerts'
complete -c noctalia -n '__noctalia_exact_path msg' -f -a 'workspace-switch' -d 'Switch to the adjacent workspace on the target monitor (stops at both ends)'
complete -c noctalia -n '__noctalia_path_prefix msg' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg bar-auto-hide-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg bar-auto-hide-set' -f -a 'on off smart true false 1 0'
complete -c noctalia -n '__noctalia_path_prefix msg bar-hide' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg bar-layer-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg bar-layer-set' -f -a 'top overlay'
complete -c noctalia -n '__noctalia_path_prefix msg bar-reserve-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg bar-show' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg bar-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg bluetooth-disable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg bluetooth-enable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg bluetooth-status' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg bluetooth-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg brightness-down' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg brightness-list-backlight-devices' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg brightness-osd' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg brightness-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg brightness-up' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg caffeine-disable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg caffeine-enable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg caffeine-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg clipboard-clear' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg clipboard-copy' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg clipboard-text' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg color-scheme-get' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_exact_path msg color-scheme-set' -f -a 'builtin' -d 'Use a built-in palette'
complete -c noctalia -n '__noctalia_exact_path msg color-scheme-set' -f -a 'wallpaper' -d 'Use a wallpaper generator scheme'
complete -c noctalia -n '__noctalia_exact_path msg color-scheme-set' -f -a 'community' -d 'Use a community palette'
complete -c noctalia -n '__noctalia_exact_path msg color-scheme-set' -f -a 'custom' -d 'Use a custom palette'
complete -c noctalia -n '__noctalia_path_prefix msg color-scheme-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg color-scheme-set builtin' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg color-scheme-set builtin' -f -a 'Ayu Catppuccin Dracula Eldritch Gruvbox Kanagawa Noctalia Nord "Rosé Pine" Tokyo-Night'
complete -c noctalia -n '__noctalia_path_prefix msg color-scheme-set wallpaper' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg color-scheme-set wallpaper' -f -a 'm3-tonal-spot m3-content m3-fruit-salad m3-rainbow m3-monochrome vibrant faithful soft dysfunctional muted'
complete -c noctalia -n '__noctalia_path_prefix msg color-scheme-set community' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg color-scheme-set custom' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg config-reload' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg desktop-widgets-edit' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg desktop-widgets-exit' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg desktop-widgets-hide' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg desktop-widgets-show' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg desktop-widgets-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg desktop-widgets-toggle-edit' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg dock-hide' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg dock-reload' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg dock-show' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg dock-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg dpms-off' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg dpms-on' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg effects-profile-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg effects-profile-set' -f -a 'output input'
complete -c noctalia -n '__noctalia_path_prefix msg greeter-sync' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg keyboard-backlight-down' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg keyboard-backlight-osd' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg keyboard-backlight-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg keyboard-backlight-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg keyboard-backlight-up' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg keyboard-layout-cycle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg lockscreen-widgets-edit' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg lockscreen-widgets-exit' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg lockscreen-widgets-toggle-edit' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg log-level-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg log-level-set' -f -a 'debug info warn error'
complete -c noctalia -n '__noctalia_path_prefix msg log-level-status' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg media' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg media' -f -a 'next previous toggle play pause stop next-player previous-player'
complete -c noctalia -n '__noctalia_path_prefix msg mic-mute' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg mic-volume-down' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg mic-volume-osd' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg mic-volume-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg mic-volume-up' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg network-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg nightlight-disable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg nightlight-enable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg nightlight-force-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg nightlight-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg notification-clear-active' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg notification-clear-history' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg notification-dnd-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg notification-dnd-set' -f -a 'on off true false 1 0'
complete -c noctalia -n '__noctalia_path_prefix msg notification-dnd-status' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg notification-dnd-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg notification-invoke-latest' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg notification-show' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg osd-disable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg osd-enable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg osd-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg panel-close' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg panel-open' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg panel-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg plugin' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg plugin' -f -a '(__noctalia_plugin_prefix)'
complete -c noctalia -n '__noctalia_exact_path msg plugins' -f -a 'list' -d 'List installed plugins'
complete -c noctalia -n '__noctalia_exact_path msg plugins' -f -a 'enable' -d 'Enable a plugin'
complete -c noctalia -n '__noctalia_exact_path msg plugins' -f -a 'disable' -d 'Disable a plugin'
complete -c noctalia -n '__noctalia_exact_path msg plugins' -f -a 'update' -d 'Update a plugin source'
complete -c noctalia -n '__noctalia_exact_path msg plugins' -f -a 'source' -d 'Manage plugin sources'
complete -c noctalia -n '__noctalia_path_prefix msg plugins' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg plugins list' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg plugins enable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg plugins enable' -f -a '(__noctalia_plugins_disabled)'
complete -c noctalia -n '__noctalia_path_prefix msg plugins disable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg plugins disable' -f -a '(__noctalia_plugins_enabled)'
complete -c noctalia -n '__noctalia_path_prefix msg plugins update' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_exact_path msg plugins source' -f -a 'list' -d 'List plugin sources'
complete -c noctalia -n '__noctalia_exact_path msg plugins source' -f -a 'add' -d 'Add a plugin source'
complete -c noctalia -n '__noctalia_exact_path msg plugins source' -f -a 'remove' -d 'Remove a plugin source'
complete -c noctalia -n '__noctalia_path_prefix msg plugins source' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg plugins source list' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg plugins source add' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 1 msg plugins source add' -f -a 'git path'
complete -c noctalia -n '__noctalia_path_prefix msg plugins source remove' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg power-cycle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg power-cycle' -f -a 'next prev'
complete -c noctalia -n '__noctalia_path_prefix msg power-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg screenshot-fullscreen' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg screenshot-fullscreen' -f -a 'pick monitor all'
complete -c noctalia -n '__noctalia_path_prefix msg screenshot-region' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg session' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg session' -f -a 'lock suspend lock-and-suspend logout reboot shutdown'
complete -c noctalia -n '__noctalia_path_prefix msg settings-close' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg settings-open' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg settings-open-plugin' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg settings-open-widget' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg settings-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg status' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg taskbar-cycle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg taskbar-cycle' -f -a 'next prev'
complete -c noctalia -n '__noctalia_path_prefix msg templates-apply' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg theme-mode-get' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg theme-mode-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg theme-mode-set' -f -a 'dark light auto'
complete -c noctalia -n '__noctalia_path_prefix msg theme-mode-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg volume-down' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg volume-mute' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg volume-osd' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg volume-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg volume-up' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg wallpaper-get' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg wallpaper-next' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg wallpaper-previous' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg wallpaper-random' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg wallpaper-set' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg wifi-disable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg wifi-enable' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg wifi-status' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg wifi-toggle' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg window-switcher' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg workspace-alert-add' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg workspace-alert-add-window' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg workspace-alert-clear' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg workspace-alert-clear-all' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg workspace-alert-status' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix msg workspace-switch' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_at_pos 0 msg workspace-switch' -f -a 'next prev'
complete -c noctalia -n '__noctalia_exact_path plugins' -f -a 'lint' -d 'Cross-check declared settings against plugin code'
complete -c noctalia -n '__noctalia_path_prefix plugins' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix plugins lint' -s h -l help -d 'Show this help message'
complete -c noctalia -n '__noctalia_path_prefix theme' -l scheme -r -a 'm3-tonal-spot m3-content m3-fruit-salad m3-rainbow m3-monochrome vibrant faithful soft dysfunctional muted' -d 'Color generation scheme'
complete -c noctalia -n '__noctalia_path_prefix theme' -l dark -d 'Emit only the dark variant'
complete -c noctalia -n '__noctalia_path_prefix theme' -l light -d 'Emit only the light variant'
complete -c noctalia -n '__noctalia_path_prefix theme' -l both -d 'Emit both variants under dark/light keys'
complete -c noctalia -n '__noctalia_path_prefix theme' -l pure-black -d 'Re-anchor the dark surface ramp to true black (OLED)'
complete -c noctalia -n '__noctalia_path_prefix theme' -l theme-json -r -F -d 'Load precomputed dark/light token maps from JSON'
complete -c noctalia -n '__noctalia_path_prefix theme' -s o -r -F -d 'Write JSON to file instead of stdout'
complete -c noctalia -n '__noctalia_path_prefix theme' -s r -l render -r -F -d 'Render a template file to an output path'
complete -c noctalia -n '__noctalia_path_prefix theme' -s c -l config -r -F -d 'Process a TOML template config file'
complete -c noctalia -n '__noctalia_path_prefix theme' -l builtin-config -d 'Process the shipped built-in template catalog'
complete -c noctalia -n '__noctalia_path_prefix theme' -l list-templates -d 'List built-in, cached community, and configured user templates'
complete -c noctalia -n '__noctalia_path_prefix theme' -l default-mode -r -a 'dark light' -d 'Template default mode'
complete -c noctalia -n '__noctalia_path_prefix theme' -s h -l help -d 'Show this help message'
