name = "actions"
name_pretty = "Actions"
icon = "action"

[[entries]]
text = "1. Themes"
# icon = "color-fill-symbolic"
icon = "/home/nino/.local/share/icons/material/color_palette.svg"
actions = { "toggle" = "walker --provider menus:themes" }

[[entries]]
text = "2. Color Picker"
# icon = "color-picker-symbolic"
icon = "/home/nino/.local/share/icons/material/color_picker.svg"
actions = { "toggle" = "sh -c 'sleep 0.15 && hyprpicker'" }

[[entries]]
text = "3. Logout"
# icon = "system-shutdown-symbolic"
icon = "/home/nino/.local/share/icons/material/logout.svg"
actions = { "toggle" = "fish -c logout" }

[[entries]]
text = "4. Reboot"
# icon = "system-reboot-symbolic"
icon = "/home/nino/.local/share/icons/material/reboot.svg"
actions = { "toggle" = "systemctl reboot" }

[[entries]]
text = "5. Shutdown"
# icon = "system-shutdown-symbolic"
icon = "/home/nino/.local/share/icons/material/power.svg"
actions = { "toggle" = "systemctl poweroff" }

