#!/usr/bin/env bash   
# @vicinae.schemaVersion 1
# @vicinae.exec ["/bin/bash"]
# @vicinae.title Screenshot
# @vicinae.mode silent
# @vicinae.icon /home/nino/.config/vicinae/icons/screenshot-selection-icon.png

vicinae close
sleep 0.2
noctalia msg screenshot-region
