# vim: set ft=tmux:

set -g @resurrect-save 'A'
set -g @resurrect-restore 'Z'

# For pi-coding-agent
set -g extended-keys on
set -g extended-keys-format csi-u

# Set up tmux copy mode to use vim bindings
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key v copy-mode

bind-key t choose-tree -Zw
bind-key f display-popup -E "~/.config/tmux/scripts/window-search.sh"

# Set up panes keybings to be closer to to vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# unbind &
# unbind 1
# unbind 2
# unbind 3
# unbind 4
# unbind 5
# unbind 6
# unbind 7
# unbind 8
# unbind 9
#
# bind 1 kill-window
# bind & select-window -t 1
# bind é select-window -t 2
# bind "\"" select-window -t 3
# bind "'" select-window -t 4
# bind ( select-window -t 5
# bind § select-window -t 6
# bind è select-window -t 7
# bind ! select-window -t 8
# bind ç select-window -t 9
