# vim: set ft=tmux:

set -g @resurrect-save 'A'
set -g @resurrect-restore 'Z'

# Set up tmux copy mode to use vim bindings
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -n C-y copy-mode

# Set up panes keybings to be closer to to vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind &
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9

bind 1 kill-window
bind & select-window -t 1
bind é select-window -t 2
bind "\"" select-window -t 3
bind "'" select-window -t 4
bind ( select-window -t 5
bind § select-window -t 6
bind è select-window -t 7
bind ! select-window -t 8
bind ç select-window -t 9

