[ids]

*

[main]

# Only use oneshot for meta and control
# Leave shift as normal since it breaks gaming
meta = oneshot(meta)
control = oneshot(control)

# Invert ; and :
semicolon = :

# Invert \ and |
backslash = |

[shift]
# Invert \ and |
backslash = backslash
