// Catppuccin Mocha Palette Definition
const palette = {
  // Backgrounds
  bg0: '181825',
  bg1: '1e1e2e',
  bg2: '313244',
  bg3: '45475a',
  bg4: '585b70',

  // Foregrounds
  fg: 'cdd6f4',
  fg2: 'bac2de',

  // Accents
  red: 'f38ba8',
  orange: 'fab387',
  yellow: 'f9e2af',
  green: 'a6e3a1',
  aqua: '94e2d5',
  blue: '89b4fa',
  purple: 'cba6f7',
  pink: 'f5c2e7',
  lavender: 'b4befe',

  // Greys
  grey0: '6c7086',
  grey1: '7f849c',
  grey2: '9399b2',

  // Semantic
  primary: '89b4fa'
} as const;

type Palette = typeof palette;

// Helper to create hex color with optional alpha
const c = (color: keyof Palette, alpha?: string) => {
  const hex = palette[color];
  return alpha ? `#${hex}${alpha}` : `#${hex}`;
};

// HyprPanel Theme Configuration
const theme = {
  // Bar
  'theme.bar.menus.background': c('bg1'),
  'theme.bar.background': c('bg1'),
  'theme.bar.menus.text': c('fg'),
  'theme.bar.menus.border.color': c('bg2'),
  'theme.bar.buttons.background': c('bg0'),
  'theme.bar.buttons.text': c('fg'),
  'theme.bar.buttons.icon': c('grey2'),
  'theme.bar.buttons.hover': c('bg3'),
  'theme.bar.buttons.icon_background': c('bg0'),
  'theme.bar.buttons.borderColor': c('primary'),

  // Media
  'theme.bar.buttons.media.background': c('bg0'),
  'theme.bar.buttons.media.icon': c('fg'),
  'theme.bar.buttons.media.text': c('fg'),
  'theme.bar.buttons.media.hover': c('bg3'),
  'theme.bar.buttons.media.border': c('primary'),
  'theme.bar.menus.menu.media.background.color': c('bg1'),
  'theme.bar.menus.menu.media.card.color': c('bg0'),
  'theme.bar.menus.menu.media.border.color': c('bg2'),
  'theme.bar.menus.menu.media.song': c('primary'),
  'theme.bar.menus.menu.media.artist': c('grey2'),
  'theme.bar.menus.menu.media.album': c('fg'),
  'theme.bar.menus.menu.media.timestamp': c('grey2'),
  'theme.bar.menus.menu.media.slider.primary': c('pink'),
  'theme.bar.menus.menu.media.slider.background': c('bg0'),
  'theme.bar.menus.menu.media.slider.backgroundhover': c('bg3'),
  'theme.bar.menus.menu.media.slider.puck': c('grey0'),
  'theme.bar.menus.menu.media.buttons.text': c('bg0'),
  'theme.bar.menus.menu.media.buttons.background': c('primary'),
  'theme.bar.menus.menu.media.buttons.enabled': c('aqua'),
  'theme.bar.menus.menu.media.buttons.inactive': c('grey0'),

  // Volume
  'theme.bar.menus.menu.volume.text': c('fg'),
  'theme.bar.menus.menu.volume.card.color': c('bg0'),
  'theme.bar.menus.menu.volume.label.color': c('primary'),
  'theme.bar.menus.menu.volume.border.color': c('bg2'),
  'theme.bar.menus.menu.volume.background.color': c('bg1'),
  'theme.bar.menus.menu.volume.audio_slider.primary': c('primary'),
  'theme.bar.menus.menu.volume.audio_slider.background': c('bg0'),
  'theme.bar.menus.menu.volume.audio_slider.backgroundhover': c('bg3'),
  'theme.bar.menus.menu.volume.audio_slider.puck': c('grey0'),
  'theme.bar.menus.menu.volume.input_slider.primary': c('pink'),
  'theme.bar.menus.menu.volume.input_slider.background': c('bg0'),
  'theme.bar.menus.menu.volume.input_slider.backgroundhover': c('bg3'),
  'theme.bar.menus.menu.volume.input_slider.puck': c('grey0'),
  'theme.bar.menus.menu.volume.icons.active': c('primary'),
  'theme.bar.menus.menu.volume.icons.passive': c('grey2'),
  'theme.bar.menus.menu.volume.iconbutton.active': c('primary'),
  'theme.bar.menus.menu.volume.iconbutton.passive': c('grey2'),
  'theme.bar.menus.menu.volume.listitems.active': c('primary'),
  'theme.bar.menus.menu.volume.listitems.passive': c('fg'),
  'theme.bar.buttons.volume.background': c('bg0'),
  'theme.bar.buttons.volume.icon': c('primary'),
  'theme.bar.buttons.volume.text': c('primary'),
  'theme.bar.buttons.volume.hover': c('bg3'),
  'theme.bar.buttons.volume.border': c('primary'),

  // Notifications
  'theme.bar.menus.menu.notifications.background': c('bg1'),
  'theme.bar.menus.menu.notifications.card': c('bg0'),
  'theme.bar.menus.menu.notifications.border': c('bg2'),
  'theme.bar.menus.menu.notifications.label': c('fg'),
  'theme.bar.menus.menu.notifications.no_notifications_label': c('grey2'),
  'theme.bar.menus.menu.notifications.clear': c('red'),
  'theme.bar.menus.menu.notifications.switch.enabled': c('primary'),
  'theme.bar.menus.menu.notifications.switch.disabled': c('bg0'),
  'theme.bar.menus.menu.notifications.switch.puck': c('bg3'),
  'theme.bar.menus.menu.notifications.switch_divider': c('bg2'),
  'theme.bar.menus.menu.notifications.pager.button': c('primary'),
  'theme.bar.menus.menu.notifications.pager.label': c('grey2'),
  'theme.bar.menus.menu.notifications.pager.background': c('bg0'),
  'theme.bar.menus.menu.notifications.scrollbar.color': c('primary'),
  'theme.bar.buttons.notifications.background': c('bg0'),
  'theme.bar.buttons.notifications.icon': c('fg2'),
  'theme.bar.buttons.notifications.total': c('red'),
  'theme.bar.buttons.notifications.hover': c('bg3'),
  'theme.bar.buttons.notifications.border': c('primary'),

  // Battery
  'theme.bar.menus.menu.battery.background.color': c('bg0'),
  'theme.bar.menus.menu.battery.card.color': c('bg0'),
  'theme.bar.menus.menu.battery.border.color': c('bg2'),
  'theme.bar.menus.menu.battery.text': c('fg'),
  'theme.bar.menus.menu.battery.label.color': c('yellow'),
  'theme.bar.menus.menu.battery.icons.active': c('yellow'),
  'theme.bar.menus.menu.battery.icons.passive': c('grey2'),
  'theme.bar.menus.menu.battery.listitems.active': c('yellow'),
  'theme.bar.menus.menu.battery.listitems.passive': c('fg'),
  'theme.bar.menus.menu.battery.slider.primary': c('yellow'),
  'theme.bar.menus.menu.battery.slider.background': c('bg0'),
  'theme.bar.menus.menu.battery.slider.backgroundhover': c('bg3'),
  'theme.bar.menus.menu.battery.slider.puck': c('grey0'),
  'theme.bar.buttons.battery.background': c('bg0'),
  'theme.bar.buttons.battery.icon': c('yellow'),
  'theme.bar.buttons.battery.text': c('yellow'),
  'theme.bar.buttons.battery.hover': c('bg3'),
  'theme.bar.buttons.battery.border': c('yellow'),

  // Bluetooth
  'theme.bar.menus.menu.bluetooth.background.color': c('bg1'),
  'theme.bar.menus.menu.bluetooth.card.color': c('bg0'),
  'theme.bar.menus.menu.bluetooth.border.color': c('bg2'),
  'theme.bar.menus.menu.bluetooth.text': c('fg'),
  'theme.bar.menus.menu.bluetooth.label.color': c('aqua'),
  'theme.bar.menus.menu.bluetooth.status': c('grey0'),
  'theme.bar.menus.menu.bluetooth.icons.active': c('aqua'),
  'theme.bar.menus.menu.bluetooth.icons.passive': c('grey2'),
  'theme.bar.menus.menu.bluetooth.iconbutton.active': c('aqua'),
  'theme.bar.menus.menu.bluetooth.iconbutton.passive': c('grey2'),
  'theme.bar.menus.menu.bluetooth.listitems.active': c('aqua'),
  'theme.bar.menus.menu.bluetooth.listitems.passive': c('fg'),
  'theme.bar.menus.menu.bluetooth.switch.enabled': c('aqua'),
  'theme.bar.menus.menu.bluetooth.switch.disabled': c('bg0'),
  'theme.bar.menus.menu.bluetooth.switch.puck': c('bg3'),
  'theme.bar.menus.menu.bluetooth.switch_divider': c('bg2'),
  'theme.bar.menus.menu.bluetooth.scroller.color': c('aqua'),
  'theme.bar.buttons.bluetooth.background': c('bg0'),
  'theme.bar.buttons.bluetooth.icon': c('aqua'),
  'theme.bar.buttons.bluetooth.text': c('aqua'),
  'theme.bar.buttons.bluetooth.hover': c('bg3'),
  'theme.bar.buttons.bluetooth.border': c('aqua'),

  // Network
  'theme.bar.menus.menu.network.background.color': c('bg1'),
  'theme.bar.menus.menu.network.card.color': c('bg0'),
  'theme.bar.menus.menu.network.border.color': c('bg2'),
  'theme.bar.menus.menu.network.text': c('fg'),
  'theme.bar.menus.menu.network.label.color': c('purple'),
  'theme.bar.menus.menu.network.status.color': c('grey0'),
  'theme.bar.menus.menu.network.icons.active': c('purple'),
  'theme.bar.menus.menu.network.icons.passive': c('grey2'),
  'theme.bar.menus.menu.network.iconbuttons.active': c('purple'),
  'theme.bar.menus.menu.network.iconbuttons.passive': c('grey2'),
  'theme.bar.menus.menu.network.listitems.active': c('purple'),
  'theme.bar.menus.menu.network.listitems.passive': c('fg'),
  'theme.bar.menus.menu.network.scroller.color': c('purple'),
  'theme.bar.menus.menu.network.switch.enabled': c('purple'),
  'theme.bar.menus.menu.network.switch.disabled': c('bg0'),
  'theme.bar.menus.menu.network.switch.puck': c('bg3'),
  'theme.bar.buttons.network.background': c('bg0'),
  'theme.bar.buttons.network.icon': c('purple'),
  'theme.bar.buttons.network.text': c('purple'),
  'theme.bar.buttons.network.hover': c('bg3'),
  'theme.bar.buttons.network.border': c('purple'),

  // Clock
  'theme.bar.menus.menu.clock.background.color': c('bg1'),
  'theme.bar.menus.menu.clock.card.color': c('bg0'),
  'theme.bar.menus.menu.clock.border.color': c('bg2'),
  'theme.bar.menus.menu.clock.text': c('fg'),
  'theme.bar.menus.menu.clock.time.time': c('pink'),
  'theme.bar.menus.menu.clock.time.timeperiod': c('aqua'),
  'theme.bar.menus.menu.clock.calendar.yearmonth': c('aqua'),
  'theme.bar.menus.menu.clock.calendar.weekdays': c('pink'),
  'theme.bar.menus.menu.clock.calendar.days': c('fg'),
  'theme.bar.menus.menu.clock.calendar.currentday': c('pink'),
  'theme.bar.menus.menu.clock.calendar.contextdays': c('grey2'),
  'theme.bar.menus.menu.clock.calendar.paginator': c('pink'),
  'theme.bar.menus.menu.clock.weather.icon': c('pink'),
  'theme.bar.menus.menu.clock.weather.temperature': c('fg'),
  'theme.bar.menus.menu.clock.weather.status': c('aqua'),
  'theme.bar.menus.menu.clock.weather.stats': c('pink'),
  'theme.bar.menus.menu.clock.weather.hourly.time': c('pink'),
  'theme.bar.menus.menu.clock.weather.hourly.icon': c('pink'),
  'theme.bar.menus.menu.clock.weather.hourly.temperature': c('pink'),
  'theme.bar.menus.menu.clock.weather.thermometer.extremelycold': c('blue'),
  'theme.bar.menus.menu.clock.weather.thermometer.cold': c('blue'),
  'theme.bar.menus.menu.clock.weather.thermometer.moderate': c('primary'),
  'theme.bar.menus.menu.clock.weather.thermometer.hot': c('orange'),
  'theme.bar.menus.menu.clock.weather.thermometer.extremelyhot': c('red'),
  'theme.bar.buttons.clock.background': c('bg0'),
  'theme.bar.buttons.clock.icon': c('primary'),
  'theme.bar.buttons.clock.text': c('primary'),
  'theme.bar.buttons.clock.hover': c('bg3'),
  'theme.bar.buttons.clock.border': c('pink'),

  // Dashboard
  'theme.bar.menus.menu.dashboard.background.color': c('bg1'),
  'theme.bar.menus.menu.dashboard.card.color': c('bg0'),
  'theme.bar.menus.menu.dashboard.border.color': c('bg2'),
  'theme.bar.menus.menu.dashboard.profile.name': c('pink'),
  'theme.bar.menus.menu.dashboard.powermenu.shutdown': c('red'),
  'theme.bar.menus.menu.dashboard.powermenu.restart': c('orange'),
  'theme.bar.menus.menu.dashboard.powermenu.logout': c('green'),
  'theme.bar.menus.menu.dashboard.powermenu.sleep': c('aqua'),
  'theme.bar.menus.menu.dashboard.powermenu.confirmation.background': c('bg1'),
  'theme.bar.menus.menu.dashboard.powermenu.confirmation.card': c('bg0'),
  'theme.bar.menus.menu.dashboard.powermenu.confirmation.border': c('bg2'),
  'theme.bar.menus.menu.dashboard.powermenu.confirmation.label': c('pink'),
  'theme.bar.menus.menu.dashboard.powermenu.confirmation.body': c('fg'),
  'theme.bar.menus.menu.dashboard.powermenu.confirmation.confirm': c('green'),
  'theme.bar.menus.menu.dashboard.powermenu.confirmation.deny': c('red'),
  'theme.bar.menus.menu.dashboard.powermenu.confirmation.button_text': c('bg0'),
  'theme.bar.menus.menu.dashboard.controls.wifi.background': c('purple'),
  'theme.bar.menus.menu.dashboard.controls.wifi.text': c('bg0'),
  'theme.bar.menus.menu.dashboard.controls.bluetooth.background': c('aqua'),
  'theme.bar.menus.menu.dashboard.controls.bluetooth.text': c('bg0'),
  'theme.bar.menus.menu.dashboard.controls.notifications.background':
    c('yellow'),
  'theme.bar.menus.menu.dashboard.controls.notifications.text': c('bg0'),
  'theme.bar.menus.menu.dashboard.controls.volume.background': c('pink'),
  'theme.bar.menus.menu.dashboard.controls.volume.text': c('bg0'),
  'theme.bar.menus.menu.dashboard.controls.input.background': c('pink'),
  'theme.bar.menus.menu.dashboard.controls.input.text': c('bg0'),
  'theme.bar.menus.menu.dashboard.controls.disabled': c('bg3'),
  'theme.bar.menus.menu.dashboard.shortcuts.background': c('primary'),
  'theme.bar.menus.menu.dashboard.shortcuts.text': c('bg0'),
  'theme.bar.menus.menu.dashboard.shortcuts.recording': c('red'),
  'theme.bar.menus.menu.dashboard.directories.left.top.color': c('pink'),
  'theme.bar.menus.menu.dashboard.directories.left.middle.color': c('yellow'),
  'theme.bar.menus.menu.dashboard.directories.left.bottom.color': c('red'),
  'theme.bar.menus.menu.dashboard.directories.right.top.color': c('aqua'),
  'theme.bar.menus.menu.dashboard.directories.right.middle.color': c('purple'),
  'theme.bar.menus.menu.dashboard.directories.right.bottom.color': c('primary'),
  'theme.bar.menus.menu.dashboard.monitors.bar_background': c('bg3'),
  'theme.bar.menus.menu.dashboard.monitors.cpu.icon': c('red'),
  'theme.bar.menus.menu.dashboard.monitors.cpu.bar': c('red'),
  'theme.bar.menus.menu.dashboard.monitors.cpu.label': c('red'),
  'theme.bar.menus.menu.dashboard.monitors.ram.icon': c('yellow'),
  'theme.bar.menus.menu.dashboard.monitors.ram.bar': c('yellow'),
  'theme.bar.menus.menu.dashboard.monitors.ram.label': c('yellow'),
  'theme.bar.menus.menu.dashboard.monitors.gpu.icon': c('green'),
  'theme.bar.menus.menu.dashboard.monitors.gpu.bar': c('green'),
  'theme.bar.menus.menu.dashboard.monitors.gpu.label': c('green'),
  'theme.bar.menus.menu.dashboard.monitors.disk.icon': c('purple'),
  'theme.bar.menus.menu.dashboard.monitors.disk.bar': c('purple'),
  'theme.bar.menus.menu.dashboard.monitors.disk.label': c('purple'),
  'theme.bar.buttons.dashboard.background': c('bg0'),
  'theme.bar.buttons.dashboard.icon': c('fg2'),
  'theme.bar.buttons.dashboard.hover': c('bg3'),
  'theme.bar.buttons.dashboard.border': c('primary'),

  // Workspaces
  'theme.bar.buttons.workspaces.background': c('bg0'),
  'theme.bar.buttons.workspaces.active': c('primary'),
  'theme.bar.buttons.workspaces.occupied': c('bg2'),
  'theme.bar.buttons.workspaces.available': c('bg2'),
  'theme.bar.buttons.workspaces.hover': c('primary'),
  'theme.bar.buttons.workspaces.border': c('pink'),
  'theme.bar.buttons.workspaces.numbered_active_underline_color': c('pink'),
  'theme.bar.buttons.workspaces.numbered_active_highlighted_text_color':
    c('bg0'),

  // Window Title
  'theme.bar.buttons.windowtitle.background': c('bg0'),
  'theme.bar.buttons.windowtitle.icon': c('yellow'),
  'theme.bar.buttons.windowtitle.text': c('yellow'),
  'theme.bar.buttons.windowtitle.hover': c('bg3'),
  'theme.bar.buttons.windowtitle.border': c('pink'),

  // Systray
  'theme.bar.buttons.systray.background': c('bg0'),
  'theme.bar.buttons.systray.hover': c('bg3'),
  'theme.bar.buttons.systray.border': c('primary'),
  'theme.bar.buttons.systray.customIcon': c('fg2'),
  'theme.bar.menus.menu.systray.dropdownmenu.background': c('bg1'),
  'theme.bar.menus.menu.systray.dropdownmenu.text': c('fg'),
  'theme.bar.menus.menu.systray.dropdownmenu.divider': c('bg2'),

  // Power Menu
  'theme.bar.menus.menu.power.background.color': c('bg1'),
  'theme.bar.menus.menu.power.border.color': c('bg2'),
  'theme.bar.menus.menu.power.buttons.shutdown.background': c('bg0'),
  'theme.bar.menus.menu.power.buttons.shutdown.text': c('red'),
  'theme.bar.menus.menu.power.buttons.shutdown.icon_background': c('red'),
  'theme.bar.menus.menu.power.buttons.shutdown.icon': c('bg0'),
  'theme.bar.menus.menu.power.buttons.restart.background': c('bg0'),
  'theme.bar.menus.menu.power.buttons.restart.text': c('orange'),
  'theme.bar.menus.menu.power.buttons.restart.icon_background': c('orange'),
  'theme.bar.menus.menu.power.buttons.restart.icon': c('bg0'),
  'theme.bar.menus.menu.power.buttons.logout.background': c('bg0'),
  'theme.bar.menus.menu.power.buttons.logout.text': c('green'),
  'theme.bar.menus.menu.power.buttons.logout.icon_background': c('green'),
  'theme.bar.menus.menu.power.buttons.logout.icon': c('bg0'),
  'theme.bar.menus.menu.power.buttons.sleep.background': c('bg0'),
  'theme.bar.menus.menu.power.buttons.sleep.text': c('aqua'),
  'theme.bar.menus.menu.power.buttons.sleep.icon_background': c('aqua'),
  'theme.bar.menus.menu.power.buttons.sleep.icon': c('bg0'),

  // OSD
  'theme.osd.bar_container': c('bg1'),
  'theme.osd.icon_container': c('primary'),
  'theme.osd.icon': c('bg0'),
  'theme.osd.label': c('primary'),
  'theme.osd.bar_color': c('primary'),
  'theme.osd.bar_empty_color': c('bg2'),
  'theme.osd.bar_overflow_color': c('red'),

  // Notifications
  'theme.notification.background': c('bg0'),
  'theme.notification.border': c('bg2'),
  'theme.notification.label': c('primary'),
  'theme.notification.text': c('fg'),
  'theme.notification.time': c('grey2'),
  'theme.notification.actions.background': c('primary'),
  'theme.notification.actions.text': c('bg0'),
  'theme.notification.close_button.background': c('red'),
  'theme.notification.close_button.label': c('bg0'),
  'theme.notification.labelicon': c('primary'),

  // Tooltips & Menus
  'theme.bar.menus.tooltip.background': c('bg1'),
  'theme.bar.menus.tooltip.text': c('fg'),
  'theme.bar.menus.popover.background': c('bg1'),
  'theme.bar.menus.popover.text': c('fg'),
  'theme.bar.menus.popover.border': c('bg0'),
  'theme.bar.menus.dropdownmenu.background': c('bg1'),
  'theme.bar.menus.dropdownmenu.text': c('fg'),
  'theme.bar.menus.dropdownmenu.divider': c('bg2'),

  // Common Elements
  'theme.bar.menus.cards': c('bg0'),
  'theme.bar.menus.label': c('primary'),
  'theme.bar.menus.feinttext': c('grey2'),
  'theme.bar.menus.dimtext': c('grey2'),
  'theme.bar.menus.listitems.active': c('primary'),
  'theme.bar.menus.listitems.passive': c('fg'),
  'theme.bar.menus.icons.active': c('primary'),
  'theme.bar.menus.icons.passive': c('grey2'),
  'theme.bar.menus.iconbuttons.active': c('primary'),
  'theme.bar.menus.iconbuttons.passive': c('grey2'),
  'theme.bar.menus.buttons.default': c('primary'),
  'theme.bar.menus.buttons.active': c('pink'),
  'theme.bar.menus.buttons.disabled': c('grey2'),
  'theme.bar.menus.buttons.text': c('bg0'),
  'theme.bar.menus.switch.enabled': c('primary'),
  'theme.bar.menus.switch.disabled': c('bg0'),
  'theme.bar.menus.switch.puck': c('bg3'),
  'theme.bar.menus.slider.primary': c('primary'),
  'theme.bar.menus.slider.background': c('bg0'),
  'theme.bar.menus.slider.backgroundhover': c('bg3'),
  'theme.bar.menus.slider.puck': c('grey0'),
  'theme.bar.menus.progressbar.foreground': c('primary'),
  'theme.bar.menus.progressbar.background': c('bg0'),
  'theme.bar.menus.check_radio_button.active': c('primary'),
  'theme.bar.menus.check_radio_button.background': c('bg1'),

  // Bar border
  'theme.bar.border.color': c('primary'),

  // Modules
  'theme.bar.buttons.modules.cpu.icon': c('red'),
  'theme.bar.buttons.modules.cpu.text': c('red'),
  'theme.bar.buttons.modules.cpu.background': c('bg0'),
  'theme.bar.buttons.modules.cpu.icon_background': c('bg0'),
  'theme.bar.buttons.modules.cpu.border': c('red'),
  'theme.bar.buttons.modules.ram.icon': c('yellow'),
  'theme.bar.buttons.modules.ram.text': c('yellow'),
  'theme.bar.buttons.modules.ram.background': c('bg0'),
  'theme.bar.buttons.modules.ram.icon_background': c('bg0'),
  'theme.bar.buttons.modules.ram.border': c('yellow'),
  'theme.bar.buttons.modules.storage.icon': c('purple'),
  'theme.bar.buttons.modules.storage.text': c('purple'),
  'theme.bar.buttons.modules.storage.background': c('bg0'),
  'theme.bar.buttons.modules.storage.icon_background': c('bg0'),
  'theme.bar.buttons.modules.storage.border': c('purple'),
  'theme.bar.buttons.modules.netstat.icon': c('green'),
  'theme.bar.buttons.modules.netstat.text': c('green'),
  'theme.bar.buttons.modules.netstat.background': c('bg0'),
  'theme.bar.buttons.modules.netstat.icon_background': c('bg0'),
  'theme.bar.buttons.modules.netstat.border': c('green'),
  'theme.bar.buttons.modules.kbLayout.icon': c('aqua'),
  'theme.bar.buttons.modules.kbLayout.text': c('aqua'),
  'theme.bar.buttons.modules.kbLayout.background': c('bg0'),
  'theme.bar.buttons.modules.kbLayout.icon_background': c('bg0'),
  'theme.bar.buttons.modules.kbLayout.border': c('aqua'),
  'theme.bar.buttons.modules.updates.icon': c('purple'),
  'theme.bar.buttons.modules.updates.text': c('purple'),
  'theme.bar.buttons.modules.updates.background': c('bg0'),
  'theme.bar.buttons.modules.updates.icon_background': c('bg0'),
  'theme.bar.buttons.modules.updates.border': c('purple'),
  'theme.bar.buttons.modules.weather.icon': c('primary'),
  'theme.bar.buttons.modules.weather.text': c('primary'),
  'theme.bar.buttons.modules.weather.background': c('bg0'),
  'theme.bar.buttons.modules.weather.icon_background': c('bg0'),
  'theme.bar.buttons.modules.weather.border': c('primary'),
  'theme.bar.buttons.modules.power.icon': c('red'),
  'theme.bar.buttons.modules.power.background': c('bg0'),
  'theme.bar.buttons.modules.power.icon_background': c('red'),
  'theme.bar.buttons.modules.power.border': c('red'),
  'theme.bar.buttons.modules.submap.icon': c('aqua'),
  'theme.bar.buttons.modules.submap.text': c('aqua'),
  'theme.bar.buttons.modules.submap.background': c('bg0'),
  'theme.bar.buttons.modules.submap.icon_background': c('bg0'),
  'theme.bar.buttons.modules.submap.border': c('aqua'),
  'theme.bar.buttons.modules.hyprsunset.icon': c('orange'),
  'theme.bar.buttons.modules.hyprsunset.text': c('orange'),
  'theme.bar.buttons.modules.hyprsunset.background': c('bg0'),
  'theme.bar.buttons.modules.hyprsunset.icon_background': c('bg0'),
  'theme.bar.buttons.modules.hyprsunset.border': c('pink'),
  'theme.bar.buttons.modules.hypridle.icon': c('pink'),
  'theme.bar.buttons.modules.hypridle.text': c('pink'),
  'theme.bar.buttons.modules.hypridle.background': c('bg0'),
  'theme.bar.buttons.modules.hypridle.icon_background': c('pink'),
  'theme.bar.buttons.modules.hypridle.border': c('pink'),
  'theme.bar.buttons.modules.cava.icon': c('aqua'),
  'theme.bar.buttons.modules.cava.text': c('aqua'),
  'theme.bar.buttons.modules.cava.background': c('bg0'),
  'theme.bar.buttons.modules.cava.icon_background': c('bg0'),
  'theme.bar.buttons.modules.cava.border': c('aqua'),
  'theme.bar.buttons.modules.worldclock.icon': c('pink'),
  'theme.bar.buttons.modules.worldclock.text': c('pink'),
  'theme.bar.buttons.modules.worldclock.background': c('bg0'),
  'theme.bar.buttons.modules.worldclock.icon_background': c('pink'),
  'theme.bar.buttons.modules.worldclock.border': c('pink'),
  'theme.bar.buttons.modules.microphone.icon': c('green'),
  'theme.bar.buttons.modules.microphone.text': c('green'),
  'theme.bar.buttons.modules.microphone.background': c('bg0'),
  'theme.bar.buttons.modules.microphone.icon_background': c('bg0'),
  'theme.bar.buttons.modules.microphone.border': c('green')
};

// Generate JSON output
const output = JSON.stringify(theme, null, 2);
console.log(output);
