XCURSOR_SIZE=24
QT_QPA_PLATFORMTHEME=qt6ct
LC_TIME=en_GB.UTF-8
CLAUDE_CONFIG_DIR="$HOME/.config/claude"
STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
PI_CODING_AGENT_DIR="$HOME/.config/pi"
XDG_CONFIG_HOME="$HOME/.config"
EZA_CONFIG_DIR="$HOME/.config/eza"
CLAUDE_CONFIG_DIR="$HOME/.config/claude"
CODEX_HOME="$HOME/.config/codex"
