# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="{{ colors.terminal_background.default.hex }}"

# Main text color
theme[main_fg]="{{ colors.terminal_foreground.default.hex }}"

# Title color for boxes
theme[title]="{{ colors.terminal_foreground.default.hex }}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{ colors.primary.default.hex }}"

# Background color of selected item in processes box
theme[selected_bg]="{{ colors.terminal_selection_bg.default.hex }}"

# Foreground color of selected item in processes box
theme[selected_fg]="{{ colors.primary.default.hex }}"

# Color of inactive/disabled text
theme[inactive_fg]="{{ colors.on_surface_variant.default.hex }}"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="{{ colors.terminal_cursor.default.hex }}"

# Background color of the percentage meters
theme[meter_bg]="{{ colors.terminal_selection_bg.default.hex }}"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{{ colors.terminal_cursor.default.hex }}"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="{{ colors.primary.default.hex }}" #Mauve
theme[mem_box]="{{ colors.tertiary.default.hex }}" #Green
theme[net_box]="{{ colors.tertiary.default.hex }}" #Maroon
theme[proc_box]="{{ colors.primary.default.hex }}" #Blue

# Box divider line and small boxes line color
theme[div_line]="{{ colors.outline.default.hex }}"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="{{ colors.terminal_normal_green.default.hex }}"
theme[temp_mid]="{{ colors.terminal_normal_yellow.default.hex }}"
theme[temp_end]="{{ colors.terminal_normal_red.default.hex }}"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="{{ colors.terminal_normal_cyan.default.hex }}"
theme[cpu_mid]="{{ colors.terminal_normal_blue.default.hex }}"
theme[cpu_end]="{{ colors.secondary.default.hex }}"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="{{ colors.tertiary.default.hex }}"
theme[free_mid]="{{ colors.secondary.default.hex }}"
theme[free_end]="{{ colors.primary.default.hex }}"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="{{ colors.terminal_normal_blue.default.hex | blend: "#74c7ec", 1 }}"
theme[cached_mid]="{{ colors.primary.default.hex }}"
theme[cached_end]="{{ colors.secondary.default.hex }}"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="{{ colors.terminal_normal_yellow.default.hex | set_hue 30 }}"
theme[available_mid]="{{ colors.terminal_normal_red.default.hex | lighten 7 }}"
theme[available_end]="{{ colors.terminal_normal_red.default.hex }}"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="{{ colors.terminal_normal_green.default.hex }}"
theme[used_mid]="{{ colors.terminal_normal_cyan.default.hex }}"
theme[used_end]="{{ colors.terminal_normal_blue.default.hex | set_hue 200 }}"

# Download graph colors (Peach -> Red)
theme[download_start]="{{ colors.terminal_normal_yellow.default.hex | set_hue 30 }}"
theme[download_mid]="{{ colors.terminal_normal_red.default.hex | lighten 7 }}"
theme[download_end]="{{ colors.terminal_normal_red.default.hex }}"

# Upload graph colors (Green -> Sky)
theme[upload_start]="{{ colors.terminal_normal_green.default.hex }}"
theme[upload_mid]="{{ colors.terminal_normal_cyan.default.hex }}"
theme[upload_end]="{{ colors.terminal_normal_blue.default.hex | set_hue 200 }}"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="{{ colors.terminal_normal_blue.default.hex }}"
theme[process_mid]="{{ colors.secondary.default.hex }}"
theme[process_end]="{{ colors.tertiary.default.hex }}"
