name = "Noctalia"

[colors]
bg_base = "{{ colors.terminal_background.dark.hex }}"
bg_active = "{{ colors.surface_variant.dark.hex }}"
primary = "{{ colors.primary.dark.hex }}"
secondary = "{{ colors.secondary.dark.hex }}"
accent = "{{ colors.primary.dark.hex }}"
warning = "{{ colors.terminal_normal_yellow.dark.hex }}"
danger = "{{ colors.error.dark.hex }}"
fg_primary = "{{ colors.on_surface.dark.hex }}"
fg_secondary = "{{ colors.on_surface.dark.hex }}"
fg_muted = "{{ colors.on_surface.dark.hex }}"
border_focus = "{{ colors.primary.dark.hex }}"
