[bar.default]
background_opacity = 0.64999998547136784
capsule_thickness = 0.69999998807907104
center = ["workspaces", "clock"]
concave_edge_corners = true
end = [
  "tray",
  "widget",
  "network",
  "bluetooth",
  "volume",
  "brightness",
  "battery",
  "notifications",
]
font_family = "Recursive Sans Casual Static"
margin_edge = 16
margin_ends = 16
start = ["control-center", "spacer_2", "group:g1", "weather", "cat", "group:g2"]
thickness = 36
widget_spacing = 10

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "primary"
id = "g1"
members = ["audio_visualizer", "media"]
opacity = 0.10000000149011612
padding = 10.0
widget_spacing = 6

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = false
fill = "surface_variant"
id = "g2"
members = ["cpu", "ram", "temp"]
opacity = 0.0
padding = 0.0
