[widget.audio_visualizer]
bands = 3
font_scale = 0.95000000000000007
mirrored = true
width = 35

[widget.bar]
extras = "none"
provider_limit = 2
style = "meter"
type = "felipeartur/ai-usagebar:bar"

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.cat]
input_devices = ["/dev/input/event*"]
type = "noctalia/bongocat:cat"

[widget.clock]
format = "{:%a %d %b %H:%M}"
timezone = "Europe/Paris"
vertical_format = "{:%a %H:%M}"

[widget.control-center]
capsule_fill = "on_primary"
capsule_padding = 9
color = "primary"
custom_image = "/home/nino/.local/share/icons/custom/cachy-os-colored.svg"
custom_image_colorize = true
glyph = ""
scale = 1.25

[widget.media]
artist_first = true
color = "primary"
font_scale = 0.95000000000000007
hide_album_art = true
hide_when_no_media = true
max_length = 200
title_scroll = "on_hover"

[widget.network]
show_vpn_label = true

[widget.spacer_2]
type = "spacer"

[widget.tray]
drawer = true
hidden = ["nm-applet", "blueman", "org.kde.StatusNotifierItem-1-1"]
match_adjacent_spacing = true

[widget.volume]
show_label = false

[widget.weather]
icon_color = "tertiary"
show_condition = false

[widget.widget]
glyph = "cloud-download"
hide_on_empty = true
type = "yuuto/arch-updater:widget"

[widget.workspaces]
empty_color = "surface_variant"
focused_output_only = true
hide_when_empty = false
occupied_color = "surface_variant"
show_labels = false
urgent_color = "error"
