#!/bin/bash

THEME="$1"

# Store current theme in config
echo "$THEME" >"$HOME/.config/current_theme"

# Send notification to the user
notify-send "Changing theme to $THEME..." ""

# Switch to main theme wallpaper
swww img --transition-type grow --transition-fps 60 --transition-step 255 "$HOME/.local/share/wallpapers/$THEME/$THEME.png"

# =======================
# MAKO
# =======================

ln -sf "$HOME/.config/colorschemes/mako/$THEME.conf" "$HOME/.config/mako/colors.conf"

# Reload mako
makoctl reload

# =======================
# HYPRLAND
# =======================

ln -sf "$HOME/.config/colorschemes/hypr/$THEME.conf" "$HOME/.config/hypr/colors.conf"

# Reload hyprland
hyprctl reload

# =======================
# HYPRPANEL
# =======================

ln -sf "$HOME/.config/colorschemes/hyprpanel/$THEME.json" "$HOME/.config/hyprpanel/theme.json"

# Set theme using hyprpanel cli
hyprpanel useTheme ~/.config/hyprpanel/theme.json

# =======================
# STARSHIP
# =======================

# Update palette in starship.toml
sed -i "s/^palette = .*/palette = '$THEME'/" "$HOME/.config/starship.toml"

# =======================
# GHOSTTY
# =======================

# Update ghostty theme config
GHOSTTY_THEME="$THEME"
case "$THEME" in
"catppuccin")
  GHOSTTY_THEME="Catppuccin Mocha"
  ;;
"rose-pine")
  GHOSTTY_THEME="Rose Pine"
  ;;
"tokyo-night")
  GHOSTTY_THEME="TokyoNight Moon"
  ;;
esac
sed -i "s/^theme = .*/theme = ${GHOSTTY_THEME}/" "$HOME/.config/ghostty/theme"

# Reload ghostty
~/.local/bin/reload_ghostty

# =======================
# FISH
# =======================

# Update fish theme
fish -c "fish_theme \"$HOME/.config/fish/themes/$THEME.fish\""

# =======================
# FASTFETCH
# =======================

# Update fastfetch config
ln -sf "$HOME/.config/colorschemes/fastfetch/$THEME.jsonc" "$HOME/.config/fastfetch/config.jsonc"
